const { withAppBuildGradle, withGradleProperties } = require('expo/config-plugins');

// Chatly ships LiveKit/WebRTC and Google Sign-In, whose AARs contain prebuilt
// .so files for every Android ABI. A sideloaded APK keeps all of them (Google
// Play would split them per architecture automatically), which is where most
// of the download size goes. This plugin pins the packaged ABIs instead.
//
// Configure in app.json:
//
//   ["./plugins/withAbiSplits", { "abis": ["arm64-v8a", "armeabi-v7a"] }]
//
// `arm64-v8a` covers essentially every phone sold since ~2017; `armeabi-v7a`
// keeps older/budget 32-bit devices installable. The two x86 ABIs are emulator
// only, so they are excluded by default.
//
// Override for a single build without touching config (handy for emulators):
//   ./gradlew assembleRelease -Pchatly.abiFilters=x86_64
const DEFAULT_ABIS = ['arm64-v8a', 'armeabi-v7a'];

const MARKER = '// @generated by plugins/withAbiSplits.js';

const GRADLE_SNIPPET = `
${MARKER}
// Native libraries are filtered here rather than in android/gradle.properties
// because abiFilters is the only thing that removes prebuilt AAR ABIs from the
// package; reactNativeArchitectures alone still leaves them in place.
def chatlyAbis = (findProperty('chatly.abiFilters') ?: '${DEFAULT_ABIS.join(',')}')
    .split(',')
    .collect { it.trim() }
    .findAll { it }

if (chatlyAbis.isEmpty()) {
    throw new GradleException('[Chatly] chatly.abiFilters resolved to an empty list - refusing to build.')
}

android {
    defaultConfig {
        ndk {
            abiFilters(*chatlyAbis)
        }
    }
}
`;

module.exports = function withAbiSplits(config, props = {}) {
  const abis = Array.isArray(props.abis) && props.abis.length ? props.abis : DEFAULT_ABIS;

  // Keep the RN core build in sync: it compiles/builds its own libraries per
  // architecture, so trimming this list also shortens local build times.
  config = withGradleProperties(config, (config) => {
    const values = {
      reactNativeArchitectures: abis.join(','),
      'chatly.abiFilters': abis.join(','),
    };

    for (const [key, value] of Object.entries(values)) {
      const existing = config.modResults.find(
        (item) => item.type === 'property' && item.key === key,
      );

      if (existing) {
        existing.value = value;
      } else {
        config.modResults.push({ type: 'property', key, value });
      }
    }

    return config;
  });

  config = withAppBuildGradle(config, (config) => {
    if (config.modResults.language !== 'groovy') {
      throw new Error('withAbiSplits: expected a Groovy android/app/build.gradle');
    }

    // Idempotent: `expo prebuild` runs repeatedly over the same generated file.
    if (!config.modResults.contents.includes(MARKER)) {
      config.modResults.contents += GRADLE_SNIPPET;
    }

    return config;
  });

  return config;
};
