-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "signupCodeHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "signupCodeExpiresAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "resetCodeHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "resetCodeExpiresAt" TIMESTAMP(3);
